
* DONE Add the simplify plugin for simpler API
CLOSED: [2024-11-26 Tue 18:37]

https://github.com/graphile/pg-simplify-inflector

* TODO Figure out why a Subscription, and a Query does not update eachother

https://relay.dev/docs/guided-tour/updating-data/graphql-subscriptions/#refreshing-components-in-response-to-subscription-events

Everything I've read from the documentation says this should work transparently!

However, I have not been able to make it work, and that is annoying! The
component is not getting re-rendered.

Hence, give this another try at some point. Maybe this can be done in accordance with testing.

It also means I have to figure out more how Relay actually works, and handles the internal data-representation.

* TODO Look into how refreshing queries would work

https://relay.dev/docs/guided-tour/refetching/refreshing-queries/

* INPROGRESS Add a scorecard to the database schema

This is how we will track scores, and which courses are in a tournament.

Requires a bit of tuning to the schema, but!

* DONE - Decide if I should do upsert, or update mutations for existing scores
CLOSED: [2024-11-27 Wed 19:09]

https://github.com/einarjegorov/graphile-upsert-plugin/commit/94ea92e71e25a3c981feaa40cebcd0aad781f1af

Went with regular update mutations for now!
