apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: gitlab-container-registry-login-secret
type: kubernetes.io/dockerconfigjson
data: # Note the secret below is not encrypted
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7InVzZXJuYW1lIjoib2xlb3JoYWdlbiIsInBhc3N3b3JkIjoiZ2xwYXQtcUxTSnpBTnZ6bkpQelJuUFZIbTMiLCJhdXRoIjoiYjJ4bGIzSm9ZV2RsYmpwbmJIQmhkQzF4VEZOS2VrRk9kbnB1U2xCNlVtNVFWa2h0TXc9PSJ9fX0=
