apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skjeberg-inv-postgraphile-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  tls:
    - hosts:
      - skjeberg-invitational.com
      secretName: tls-ingress-http
  rules:
    - host: skjeberg-invitational.com
      http:
        paths:
          - path: /graphql
            pathType: Exact
            backend:
              service:
                name:  skjeberg-inv-postgraphile
                port:
                  number: 5432
