"""Exposes a URL that specifies the behaviour of this scalar."""
directive @specifiedBy(
  """The URL that specifies the behaviour of this scalar."""
  url: String!
) on SCALAR

"""
A signed eight-byte integer. The upper big integer values are greater than the
max value for a JavaScript number. Therefore all big integers will be output as
strings and not numbers.
"""
scalar BigInt

type Competition implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: UUID!
  competitionType: String!

  """Reads and enables pagination through a set of `CompetitionScore`."""
  competitionScoresByCompetitionId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `CompetitionScore`."""
    orderBy: [CompetitionScoresOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CompetitionScoreCondition
  ): CompetitionScoresConnection!
}

"""
A condition to be used against `Competition` object types. All fields are tested
for equality and combined with a logical ‘and.’
"""
input CompetitionCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `competitionType` field."""
  competitionType: String
}

"""An input for mutations affecting `Competition`"""
input CompetitionInput {
  id: UUID
  competitionType: String!
}

"""
Represents an update to a `Competition`. Fields that are set will be updated.
"""
input CompetitionPatch {
  id: UUID
  competitionType: String
}

"""A connection to a list of `Competition` values."""
type CompetitionsConnection {
  """A list of `Competition` objects."""
  nodes: [Competition!]!

  """
  A list of edges which contains the `Competition` and cursor to aid in pagination.
  """
  edges: [CompetitionsEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Competition` you could get from the connection."""
  totalCount: Int!
}

type CompetitionScore implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: UUID!
  points: BigInt!
  competitionId: UUID!
  playerId: UUID!

  """
  Reads a single `Competition` that is related to this `CompetitionScore`.
  """
  competitionByCompetitionId: Competition

  """Reads a single `Player` that is related to this `CompetitionScore`."""
  playerByPlayerId: Player
}

"""
A condition to be used against `CompetitionScore` object types. All fields are
tested for equality and combined with a logical ‘and.’
"""
input CompetitionScoreCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `points` field."""
  points: BigInt

  """Checks for equality with the object’s `competitionId` field."""
  competitionId: UUID

  """Checks for equality with the object’s `playerId` field."""
  playerId: UUID
}

"""An input for mutations affecting `CompetitionScore`"""
input CompetitionScoreInput {
  id: UUID
  points: BigInt!
  competitionId: UUID!
  playerId: UUID!
}

"""
Represents an update to a `CompetitionScore`. Fields that are set will be updated.
"""
input CompetitionScorePatch {
  id: UUID
  points: BigInt
  competitionId: UUID
  playerId: UUID
}

"""A connection to a list of `CompetitionScore` values."""
type CompetitionScoresConnection {
  """A list of `CompetitionScore` objects."""
  nodes: [CompetitionScore!]!

  """
  A list of edges which contains the `CompetitionScore` and cursor to aid in pagination.
  """
  edges: [CompetitionScoresEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """
  The count of *all* `CompetitionScore` you could get from the connection.
  """
  totalCount: Int!
}

"""A `CompetitionScore` edge in the connection."""
type CompetitionScoresEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `CompetitionScore` at the end of the edge."""
  node: CompetitionScore!
}

"""Methods to use when ordering `CompetitionScore`."""
enum CompetitionScoresOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  POINTS_ASC
  POINTS_DESC
  COMPETITION_ID_ASC
  COMPETITION_ID_DESC
  PLAYER_ID_ASC
  PLAYER_ID_DESC
  PRIMARY_KEY_ASC
  PRIMARY_KEY_DESC
}

"""A `Competition` edge in the connection."""
type CompetitionsEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Competition` at the end of the edge."""
  node: Competition!
}

"""Methods to use when ordering `Competition`."""
enum CompetitionsOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  COMPETITION_TYPE_ASC
  COMPETITION_TYPE_DESC
  PRIMARY_KEY_ASC
  PRIMARY_KEY_DESC
}

type Course implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: UUID!
  name: String!

  """Reads and enables pagination through a set of `Hole`."""
  holesByCourseId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Hole`."""
    orderBy: [HolesOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: HoleCondition
  ): HolesConnection!

  """Reads and enables pagination through a set of `Score`."""
  scoresByCourseId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Score`."""
    orderBy: [ScoresOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: ScoreCondition
  ): ScoresConnection!

  """Reads and enables pagination through a set of `CourseHandicap`."""
  courseHandicapsByCourseId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `CourseHandicap`."""
    orderBy: [CourseHandicapsOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CourseHandicapCondition
  ): CourseHandicapsConnection!
}

"""
A condition to be used against `Course` object types. All fields are tested for equality and combined with a logical ‘and.’
"""
input CourseCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `name` field."""
  name: String
}

type CourseHandicap implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: UUID!
  handicap: BigInt!
  playerId: UUID!
  courseId: UUID!
  createdAt: Datetime

  """Reads a single `Player` that is related to this `CourseHandicap`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `CourseHandicap`."""
  courseByCourseId: Course
}

"""
A condition to be used against `CourseHandicap` object types. All fields are
tested for equality and combined with a logical ‘and.’
"""
input CourseHandicapCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `handicap` field."""
  handicap: BigInt

  """Checks for equality with the object’s `playerId` field."""
  playerId: UUID

  """Checks for equality with the object’s `courseId` field."""
  courseId: UUID

  """Checks for equality with the object’s `createdAt` field."""
  createdAt: Datetime
}

"""An input for mutations affecting `CourseHandicap`"""
input CourseHandicapInput {
  id: UUID
  handicap: BigInt!
  playerId: UUID!
  courseId: UUID!
  createdAt: Datetime
}

"""
Represents an update to a `CourseHandicap`. Fields that are set will be updated.
"""
input CourseHandicapPatch {
  id: UUID
  handicap: BigInt
  playerId: UUID
  courseId: UUID
  createdAt: Datetime
}

"""A connection to a list of `CourseHandicap` values."""
type CourseHandicapsConnection {
  """A list of `CourseHandicap` objects."""
  nodes: [CourseHandicap!]!

  """
  A list of edges which contains the `CourseHandicap` and cursor to aid in pagination.
  """
  edges: [CourseHandicapsEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `CourseHandicap` you could get from the connection."""
  totalCount: Int!
}

"""A `CourseHandicap` edge in the connection."""
type CourseHandicapsEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `CourseHandicap` at the end of the edge."""
  node: CourseHandicap!
}

"""Methods to use when ordering `CourseHandicap`."""
enum CourseHandicapsOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  HANDICAP_ASC
  HANDICAP_DESC
  PLAYER_ID_ASC
  PLAYER_ID_DESC
  COURSE_ID_ASC
  COURSE_ID_DESC
  CREATED_AT_ASC
  CREATED_AT_DESC
  PRIMARY_KEY_ASC
  PRIMARY_KEY_DESC
}

"""An input for mutations affecting `Course`"""
input CourseInput {
  id: UUID
  name: String!
}

"""
Represents an update to a `Course`. Fields that are set will be updated.
"""
input CoursePatch {
  id: UUID
  name: String
}

"""A connection to a list of `Course` values."""
type CoursesConnection {
  """A list of `Course` objects."""
  nodes: [Course!]!

  """
  A list of edges which contains the `Course` and cursor to aid in pagination.
  """
  edges: [CoursesEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Course` you could get from the connection."""
  totalCount: Int!
}

"""A `Course` edge in the connection."""
type CoursesEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Course` at the end of the edge."""
  node: Course!
}

"""Methods to use when ordering `Course`."""
enum CoursesOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  NAME_ASC
  NAME_DESC
  PRIMARY_KEY_ASC
  PRIMARY_KEY_DESC
}

"""All input for the create `Competition` mutation."""
input CreateCompetitionInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `Competition` to be created by this mutation."""
  competition: CompetitionInput!
}

"""The output of our create `Competition` mutation."""
type CreateCompetitionPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Competition` that was created by this mutation."""
  competition: Competition

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Competition`. May be used by Relay 1."""
  competitionEdge(
    """The method to use when ordering `Competition`."""
    orderBy: [CompetitionsOrderBy!] = [PRIMARY_KEY_ASC]
  ): CompetitionsEdge
}

"""All input for the create `CompetitionScore` mutation."""
input CreateCompetitionScoreInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `CompetitionScore` to be created by this mutation."""
  competitionScore: CompetitionScoreInput!
}

"""The output of our create `CompetitionScore` mutation."""
type CreateCompetitionScorePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `CompetitionScore` that was created by this mutation."""
  competitionScore: CompetitionScore

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """
  Reads a single `Competition` that is related to this `CompetitionScore`.
  """
  competitionByCompetitionId: Competition

  """Reads a single `Player` that is related to this `CompetitionScore`."""
  playerByPlayerId: Player

  """An edge for our `CompetitionScore`. May be used by Relay 1."""
  competitionScoreEdge(
    """The method to use when ordering `CompetitionScore`."""
    orderBy: [CompetitionScoresOrderBy!] = [PRIMARY_KEY_ASC]
  ): CompetitionScoresEdge
}

"""All input for the create `CourseHandicap` mutation."""
input CreateCourseHandicapInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `CourseHandicap` to be created by this mutation."""
  courseHandicap: CourseHandicapInput!
}

"""The output of our create `CourseHandicap` mutation."""
type CreateCourseHandicapPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `CourseHandicap` that was created by this mutation."""
  courseHandicap: CourseHandicap

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Player` that is related to this `CourseHandicap`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `CourseHandicap`."""
  courseByCourseId: Course

  """An edge for our `CourseHandicap`. May be used by Relay 1."""
  courseHandicapEdge(
    """The method to use when ordering `CourseHandicap`."""
    orderBy: [CourseHandicapsOrderBy!] = [PRIMARY_KEY_ASC]
  ): CourseHandicapsEdge
}

"""All input for the create `Course` mutation."""
input CreateCourseInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `Course` to be created by this mutation."""
  course: CourseInput!
}

"""The output of our create `Course` mutation."""
type CreateCoursePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Course` that was created by this mutation."""
  course: Course

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Course`. May be used by Relay 1."""
  courseEdge(
    """The method to use when ordering `Course`."""
    orderBy: [CoursesOrderBy!] = [PRIMARY_KEY_ASC]
  ): CoursesEdge
}

"""All input for the create `Hole` mutation."""
input CreateHoleInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `Hole` to be created by this mutation."""
  hole: HoleInput!
}

"""The output of our create `Hole` mutation."""
type CreateHolePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Hole` that was created by this mutation."""
  hole: Hole

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Course` that is related to this `Hole`."""
  courseByCourseId: Course

  """An edge for our `Hole`. May be used by Relay 1."""
  holeEdge(
    """The method to use when ordering `Hole`."""
    orderBy: [HolesOrderBy!] = [PRIMARY_KEY_ASC]
  ): HolesEdge
}

"""All input for the create `Player` mutation."""
input CreatePlayerInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `Player` to be created by this mutation."""
  player: PlayerInput!
}

"""The output of our create `Player` mutation."""
type CreatePlayerPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Player` that was created by this mutation."""
  player: Player

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Player`. May be used by Relay 1."""
  playerEdge(
    """The method to use when ordering `Player`."""
    orderBy: [PlayersOrderBy!] = [PRIMARY_KEY_ASC]
  ): PlayersEdge
}

"""All input for the create `Score` mutation."""
input CreateScoreInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `Score` to be created by this mutation."""
  score: ScoreInput!
}

"""The output of our create `Score` mutation."""
type CreateScorePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Score` that was created by this mutation."""
  score: Score

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Player` that is related to this `Score`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `Score`."""
  courseByCourseId: Course

  """Reads a single `Hole` that is related to this `Score`."""
  holeByHoleId: Hole

  """An edge for our `Score`. May be used by Relay 1."""
  scoreEdge(
    """The method to use when ordering `Score`."""
    orderBy: [ScoresOrderBy!] = [PRIMARY_KEY_ASC]
  ): ScoresEdge
}

"""A location in a connection that can be used for resuming pagination."""
scalar Cursor

"""
A point in time as described by the [ISO
8601](https://en.wikipedia.org/wiki/ISO_8601) standard. May or may not include a timezone.
"""
scalar Datetime

"""All input for the `deleteCompetitionById` mutation."""
input DeleteCompetitionByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String
  id: UUID!
}

"""All input for the `deleteCompetition` mutation."""
input DeleteCompetitionInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Competition` to be deleted.
  """
  nodeId: ID!
}

"""The output of our delete `Competition` mutation."""
type DeleteCompetitionPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Competition` that was deleted by this mutation."""
  competition: Competition
  deletedCompetitionId: ID

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Competition`. May be used by Relay 1."""
  competitionEdge(
    """The method to use when ordering `Competition`."""
    orderBy: [CompetitionsOrderBy!] = [PRIMARY_KEY_ASC]
  ): CompetitionsEdge
}

"""All input for the `deleteCompetitionScoreById` mutation."""
input DeleteCompetitionScoreByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String
  id: UUID!
}

"""All input for the `deleteCompetitionScore` mutation."""
input DeleteCompetitionScoreInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `CompetitionScore` to be deleted.
  """
  nodeId: ID!
}

"""The output of our delete `CompetitionScore` mutation."""
type DeleteCompetitionScorePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `CompetitionScore` that was deleted by this mutation."""
  competitionScore: CompetitionScore
  deletedCompetitionScoreId: ID

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """
  Reads a single `Competition` that is related to this `CompetitionScore`.
  """
  competitionByCompetitionId: Competition

  """Reads a single `Player` that is related to this `CompetitionScore`."""
  playerByPlayerId: Player

  """An edge for our `CompetitionScore`. May be used by Relay 1."""
  competitionScoreEdge(
    """The method to use when ordering `CompetitionScore`."""
    orderBy: [CompetitionScoresOrderBy!] = [PRIMARY_KEY_ASC]
  ): CompetitionScoresEdge
}

"""All input for the `deleteCourseById` mutation."""
input DeleteCourseByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String
  id: UUID!
}

"""All input for the `deleteCourseHandicapById` mutation."""
input DeleteCourseHandicapByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String
  id: UUID!
}

"""All input for the `deleteCourseHandicap` mutation."""
input DeleteCourseHandicapInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `CourseHandicap` to be deleted.
  """
  nodeId: ID!
}

"""The output of our delete `CourseHandicap` mutation."""
type DeleteCourseHandicapPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `CourseHandicap` that was deleted by this mutation."""
  courseHandicap: CourseHandicap
  deletedCourseHandicapId: ID

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Player` that is related to this `CourseHandicap`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `CourseHandicap`."""
  courseByCourseId: Course

  """An edge for our `CourseHandicap`. May be used by Relay 1."""
  courseHandicapEdge(
    """The method to use when ordering `CourseHandicap`."""
    orderBy: [CourseHandicapsOrderBy!] = [PRIMARY_KEY_ASC]
  ): CourseHandicapsEdge
}

"""All input for the `deleteCourse` mutation."""
input DeleteCourseInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Course` to be deleted.
  """
  nodeId: ID!
}

"""The output of our delete `Course` mutation."""
type DeleteCoursePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Course` that was deleted by this mutation."""
  course: Course
  deletedCourseId: ID

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Course`. May be used by Relay 1."""
  courseEdge(
    """The method to use when ordering `Course`."""
    orderBy: [CoursesOrderBy!] = [PRIMARY_KEY_ASC]
  ): CoursesEdge
}

"""All input for the `deleteHoleById` mutation."""
input DeleteHoleByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String
  id: UUID!
}

"""All input for the `deleteHole` mutation."""
input DeleteHoleInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Hole` to be deleted.
  """
  nodeId: ID!
}

"""The output of our delete `Hole` mutation."""
type DeleteHolePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Hole` that was deleted by this mutation."""
  hole: Hole
  deletedHoleId: ID

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Course` that is related to this `Hole`."""
  courseByCourseId: Course

  """An edge for our `Hole`. May be used by Relay 1."""
  holeEdge(
    """The method to use when ordering `Hole`."""
    orderBy: [HolesOrderBy!] = [PRIMARY_KEY_ASC]
  ): HolesEdge
}

"""All input for the `deletePlayerById` mutation."""
input DeletePlayerByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String
  id: UUID!
}

"""All input for the `deletePlayer` mutation."""
input DeletePlayerInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Player` to be deleted.
  """
  nodeId: ID!
}

"""The output of our delete `Player` mutation."""
type DeletePlayerPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Player` that was deleted by this mutation."""
  player: Player
  deletedPlayerId: ID

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Player`. May be used by Relay 1."""
  playerEdge(
    """The method to use when ordering `Player`."""
    orderBy: [PlayersOrderBy!] = [PRIMARY_KEY_ASC]
  ): PlayersEdge
}

"""All input for the `deleteScoreById` mutation."""
input DeleteScoreByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String
  id: UUID!
}

"""All input for the `deleteScore` mutation."""
input DeleteScoreInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Score` to be deleted.
  """
  nodeId: ID!
}

"""The output of our delete `Score` mutation."""
type DeleteScorePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Score` that was deleted by this mutation."""
  score: Score
  deletedScoreId: ID

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Player` that is related to this `Score`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `Score`."""
  courseByCourseId: Course

  """Reads a single `Hole` that is related to this `Score`."""
  holeByHoleId: Hole

  """An edge for our `Score`. May be used by Relay 1."""
  scoreEdge(
    """The method to use when ordering `Score`."""
    orderBy: [ScoresOrderBy!] = [PRIMARY_KEY_ASC]
  ): ScoresEdge
}

type Hole implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: UUID!
  courseId: UUID!
  nr: BigInt!
  index: BigInt!
  par: BigInt!

  """Reads a single `Course` that is related to this `Hole`."""
  courseByCourseId: Course

  """Reads and enables pagination through a set of `Score`."""
  scoresByHoleId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Score`."""
    orderBy: [ScoresOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: ScoreCondition
  ): ScoresConnection!
}

"""
A condition to be used against `Hole` object types. All fields are tested for equality and combined with a logical ‘and.’
"""
input HoleCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `courseId` field."""
  courseId: UUID

  """Checks for equality with the object’s `nr` field."""
  nr: BigInt

  """Checks for equality with the object’s `index` field."""
  index: BigInt

  """Checks for equality with the object’s `par` field."""
  par: BigInt
}

"""An input for mutations affecting `Hole`"""
input HoleInput {
  id: UUID
  courseId: UUID!
  nr: BigInt!
  index: BigInt!
  par: BigInt!
}

"""Represents an update to a `Hole`. Fields that are set will be updated."""
input HolePatch {
  id: UUID
  courseId: UUID
  nr: BigInt
  index: BigInt
  par: BigInt
}

"""A connection to a list of `Hole` values."""
type HolesConnection {
  """A list of `Hole` objects."""
  nodes: [Hole!]!

  """
  A list of edges which contains the `Hole` and cursor to aid in pagination.
  """
  edges: [HolesEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Hole` you could get from the connection."""
  totalCount: Int!
}

"""A `Hole` edge in the connection."""
type HolesEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Hole` at the end of the edge."""
  node: Hole!
}

"""Methods to use when ordering `Hole`."""
enum HolesOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  COURSE_ID_ASC
  COURSE_ID_DESC
  NR_ASC
  NR_DESC
  INDEX_ASC
  INDEX_DESC
  PAR_ASC
  PAR_DESC
  PRIMARY_KEY_ASC
  PRIMARY_KEY_DESC
}

"""
The root mutation type which contains root level fields which mutate data.
"""
type Mutation {
  """Creates a single `Competition`."""
  createCompetition(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateCompetitionInput!
  ): CreateCompetitionPayload

  """Creates a single `CompetitionScore`."""
  createCompetitionScore(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateCompetitionScoreInput!
  ): CreateCompetitionScorePayload

  """Creates a single `Course`."""
  createCourse(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateCourseInput!
  ): CreateCoursePayload

  """Creates a single `CourseHandicap`."""
  createCourseHandicap(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateCourseHandicapInput!
  ): CreateCourseHandicapPayload

  """Creates a single `Hole`."""
  createHole(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateHoleInput!
  ): CreateHolePayload

  """Creates a single `Player`."""
  createPlayer(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreatePlayerInput!
  ): CreatePlayerPayload

  """Creates a single `Score`."""
  createScore(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateScoreInput!
  ): CreateScorePayload

  """
  Updates a single `Competition` using its globally unique id and a patch.
  """
  updateCompetition(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCompetitionInput!
  ): UpdateCompetitionPayload

  """Updates a single `Competition` using a unique key and a patch."""
  updateCompetitionById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCompetitionByIdInput!
  ): UpdateCompetitionPayload

  """
  Updates a single `CompetitionScore` using its globally unique id and a patch.
  """
  updateCompetitionScore(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCompetitionScoreInput!
  ): UpdateCompetitionScorePayload

  """Updates a single `CompetitionScore` using a unique key and a patch."""
  updateCompetitionScoreById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCompetitionScoreByIdInput!
  ): UpdateCompetitionScorePayload

  """Updates a single `Course` using its globally unique id and a patch."""
  updateCourse(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCourseInput!
  ): UpdateCoursePayload

  """Updates a single `Course` using a unique key and a patch."""
  updateCourseById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCourseByIdInput!
  ): UpdateCoursePayload

  """
  Updates a single `CourseHandicap` using its globally unique id and a patch.
  """
  updateCourseHandicap(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCourseHandicapInput!
  ): UpdateCourseHandicapPayload

  """Updates a single `CourseHandicap` using a unique key and a patch."""
  updateCourseHandicapById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateCourseHandicapByIdInput!
  ): UpdateCourseHandicapPayload

  """Updates a single `Hole` using its globally unique id and a patch."""
  updateHole(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateHoleInput!
  ): UpdateHolePayload

  """Updates a single `Hole` using a unique key and a patch."""
  updateHoleById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateHoleByIdInput!
  ): UpdateHolePayload

  """Updates a single `Player` using its globally unique id and a patch."""
  updatePlayer(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdatePlayerInput!
  ): UpdatePlayerPayload

  """Updates a single `Player` using a unique key and a patch."""
  updatePlayerById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdatePlayerByIdInput!
  ): UpdatePlayerPayload

  """Updates a single `Score` using its globally unique id and a patch."""
  updateScore(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateScoreInput!
  ): UpdateScorePayload

  """Updates a single `Score` using a unique key and a patch."""
  updateScoreById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: UpdateScoreByIdInput!
  ): UpdateScorePayload

  """Deletes a single `Competition` using its globally unique id."""
  deleteCompetition(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCompetitionInput!
  ): DeleteCompetitionPayload

  """Deletes a single `Competition` using a unique key."""
  deleteCompetitionById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCompetitionByIdInput!
  ): DeleteCompetitionPayload

  """Deletes a single `CompetitionScore` using its globally unique id."""
  deleteCompetitionScore(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCompetitionScoreInput!
  ): DeleteCompetitionScorePayload

  """Deletes a single `CompetitionScore` using a unique key."""
  deleteCompetitionScoreById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCompetitionScoreByIdInput!
  ): DeleteCompetitionScorePayload

  """Deletes a single `Course` using its globally unique id."""
  deleteCourse(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCourseInput!
  ): DeleteCoursePayload

  """Deletes a single `Course` using a unique key."""
  deleteCourseById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCourseByIdInput!
  ): DeleteCoursePayload

  """Deletes a single `CourseHandicap` using its globally unique id."""
  deleteCourseHandicap(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCourseHandicapInput!
  ): DeleteCourseHandicapPayload

  """Deletes a single `CourseHandicap` using a unique key."""
  deleteCourseHandicapById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteCourseHandicapByIdInput!
  ): DeleteCourseHandicapPayload

  """Deletes a single `Hole` using its globally unique id."""
  deleteHole(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteHoleInput!
  ): DeleteHolePayload

  """Deletes a single `Hole` using a unique key."""
  deleteHoleById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteHoleByIdInput!
  ): DeleteHolePayload

  """Deletes a single `Player` using its globally unique id."""
  deletePlayer(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeletePlayerInput!
  ): DeletePlayerPayload

  """Deletes a single `Player` using a unique key."""
  deletePlayerById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeletePlayerByIdInput!
  ): DeletePlayerPayload

  """Deletes a single `Score` using its globally unique id."""
  deleteScore(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteScoreInput!
  ): DeleteScorePayload

  """Deletes a single `Score` using a unique key."""
  deleteScoreById(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: DeleteScoreByIdInput!
  ): DeleteScorePayload
}

"""An object with a globally unique `ID`."""
interface Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
}

"""Information about pagination in a connection."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: Cursor

  """When paginating forwards, the cursor to continue."""
  endCursor: Cursor
}

type Player implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  id: UUID!
  name: String!

  """Reads and enables pagination through a set of `Score`."""
  scoresByPlayerId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Score`."""
    orderBy: [ScoresOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: ScoreCondition
  ): ScoresConnection!

  """Reads and enables pagination through a set of `CourseHandicap`."""
  courseHandicapsByPlayerId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `CourseHandicap`."""
    orderBy: [CourseHandicapsOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CourseHandicapCondition
  ): CourseHandicapsConnection!

  """Reads and enables pagination through a set of `CompetitionScore`."""
  competitionScoresByPlayerId(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `CompetitionScore`."""
    orderBy: [CompetitionScoresOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CompetitionScoreCondition
  ): CompetitionScoresConnection!
}

"""
A condition to be used against `Player` object types. All fields are tested for equality and combined with a logical ‘and.’
"""
input PlayerCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `name` field."""
  name: String
}

"""An input for mutations affecting `Player`"""
input PlayerInput {
  id: UUID!
  name: String!
}

"""
Represents an update to a `Player`. Fields that are set will be updated.
"""
input PlayerPatch {
  id: UUID
  name: String
}

"""A connection to a list of `Player` values."""
type PlayersConnection {
  """A list of `Player` objects."""
  nodes: [Player!]!

  """
  A list of edges which contains the `Player` and cursor to aid in pagination.
  """
  edges: [PlayersEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Player` you could get from the connection."""
  totalCount: Int!
}

"""A `Player` edge in the connection."""
type PlayersEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Player` at the end of the edge."""
  node: Player!
}

"""Methods to use when ordering `Player`."""
enum PlayersOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  NAME_ASC
  NAME_DESC
  PRIMARY_KEY_ASC
  PRIMARY_KEY_DESC
}

"""The root query type which gives access points into the data universe."""
type Query implements Node {
  """
  Exposes the root query type nested one level down. This is helpful for Relay 1
  which can only query top level fields if they are in a particular form.
  """
  query: Query!

  """
  The root query type must be a `Node` to work well with Relay 1 mutations. This just resolves to `query`.
  """
  nodeId: ID!

  """Fetches an object given its globally unique `ID`."""
  node(
    """The globally unique `ID`."""
    nodeId: ID!
  ): Node

  """Reads and enables pagination through a set of `Competition`."""
  allCompetitions(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Competition`."""
    orderBy: [CompetitionsOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CompetitionCondition
  ): CompetitionsConnection

  """Reads and enables pagination through a set of `CompetitionScore`."""
  allCompetitionScores(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `CompetitionScore`."""
    orderBy: [CompetitionScoresOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CompetitionScoreCondition
  ): CompetitionScoresConnection

  """Reads and enables pagination through a set of `Course`."""
  allCourses(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Course`."""
    orderBy: [CoursesOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CourseCondition
  ): CoursesConnection

  """Reads and enables pagination through a set of `CourseHandicap`."""
  allCourseHandicaps(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `CourseHandicap`."""
    orderBy: [CourseHandicapsOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CourseHandicapCondition
  ): CourseHandicapsConnection

  """Reads and enables pagination through a set of `Hole`."""
  allHoles(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Hole`."""
    orderBy: [HolesOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: HoleCondition
  ): HolesConnection

  """Reads and enables pagination through a set of `Player`."""
  allPlayers(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Player`."""
    orderBy: [PlayersOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: PlayerCondition
  ): PlayersConnection

  """Reads and enables pagination through a set of `Score`."""
  allScores(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Score`."""
    orderBy: [ScoresOrderBy!] = [PRIMARY_KEY_ASC]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: ScoreCondition
  ): ScoresConnection
  competitionById(id: UUID!): Competition
  competitionScoreById(id: UUID!): CompetitionScore
  courseById(id: UUID!): Course
  courseHandicapById(id: UUID!): CourseHandicap
  holeById(id: UUID!): Hole
  playerById(id: UUID!): Player
  scoreById(id: UUID!): Score
  myFunction: Int
  playerPointsTotal(id_: UUID): Int
  playerPointsTotalOnCompetitions(id_: UUID): Int
  playerPointsTotalOnCourse(id_: UUID): Int
  playerPointsTotalOnCourseSpecific(id_: UUID, courseId_: UUID): Int

  """Reads a single `Competition` using its globally unique `ID`."""
  competition(
    """
    The globally unique `ID` to be used in selecting a single `Competition`.
    """
    nodeId: ID!
  ): Competition

  """Reads a single `CompetitionScore` using its globally unique `ID`."""
  competitionScore(
    """
    The globally unique `ID` to be used in selecting a single `CompetitionScore`.
    """
    nodeId: ID!
  ): CompetitionScore

  """Reads a single `Course` using its globally unique `ID`."""
  course(
    """The globally unique `ID` to be used in selecting a single `Course`."""
    nodeId: ID!
  ): Course

  """Reads a single `CourseHandicap` using its globally unique `ID`."""
  courseHandicap(
    """
    The globally unique `ID` to be used in selecting a single `CourseHandicap`.
    """
    nodeId: ID!
  ): CourseHandicap

  """Reads a single `Hole` using its globally unique `ID`."""
  hole(
    """The globally unique `ID` to be used in selecting a single `Hole`."""
    nodeId: ID!
  ): Hole

  """Reads a single `Player` using its globally unique `ID`."""
  player(
    """The globally unique `ID` to be used in selecting a single `Player`."""
    nodeId: ID!
  ): Player

  """Reads a single `Score` using its globally unique `ID`."""
  score(
    """The globally unique `ID` to be used in selecting a single `Score`."""
    nodeId: ID!
  ): Score
}

type Score implements Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
  strokes: BigInt!
  points: BigInt!
  id: UUID!
  playerId: UUID!
  courseId: UUID!
  holeId: UUID!

  """Reads a single `Player` that is related to this `Score`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `Score`."""
  courseByCourseId: Course

  """Reads a single `Hole` that is related to this `Score`."""
  holeByHoleId: Hole
}

"""
A condition to be used against `Score` object types. All fields are tested for equality and combined with a logical ‘and.’
"""
input ScoreCondition {
  """Checks for equality with the object’s `strokes` field."""
  strokes: BigInt

  """Checks for equality with the object’s `points` field."""
  points: BigInt

  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `playerId` field."""
  playerId: UUID

  """Checks for equality with the object’s `courseId` field."""
  courseId: UUID

  """Checks for equality with the object’s `holeId` field."""
  holeId: UUID
}

"""An input for mutations affecting `Score`"""
input ScoreInput {
  strokes: BigInt!
  points: BigInt!
  id: UUID
  playerId: UUID!
  courseId: UUID!
  holeId: UUID!
}

"""
Represents an update to a `Score`. Fields that are set will be updated.
"""
input ScorePatch {
  strokes: BigInt
  points: BigInt
  id: UUID
  playerId: UUID
  courseId: UUID
  holeId: UUID
}

"""A connection to a list of `Score` values."""
type ScoresConnection {
  """A list of `Score` objects."""
  nodes: [Score!]!

  """
  A list of edges which contains the `Score` and cursor to aid in pagination.
  """
  edges: [ScoresEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Score` you could get from the connection."""
  totalCount: Int!
}

"""A `Score` edge in the connection."""
type ScoresEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Score` at the end of the edge."""
  node: Score!
}

"""Methods to use when ordering `Score`."""
enum ScoresOrderBy {
  NATURAL
  STROKES_ASC
  STROKES_DESC
  POINTS_ASC
  POINTS_DESC
  ID_ASC
  ID_DESC
  PLAYER_ID_ASC
  PLAYER_ID_DESC
  COURSE_ID_ASC
  COURSE_ID_DESC
  HOLE_ID_ASC
  HOLE_ID_DESC
  PRIMARY_KEY_ASC
  PRIMARY_KEY_DESC
}

"""All input for the `updateCompetitionById` mutation."""
input UpdateCompetitionByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  An object where the defined keys will be set on the `Competition` being updated.
  """
  competitionPatch: CompetitionPatch!
  id: UUID!
}

"""All input for the `updateCompetition` mutation."""
input UpdateCompetitionInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Competition` to be updated.
  """
  nodeId: ID!

  """
  An object where the defined keys will be set on the `Competition` being updated.
  """
  competitionPatch: CompetitionPatch!
}

"""The output of our update `Competition` mutation."""
type UpdateCompetitionPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Competition` that was updated by this mutation."""
  competition: Competition

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Competition`. May be used by Relay 1."""
  competitionEdge(
    """The method to use when ordering `Competition`."""
    orderBy: [CompetitionsOrderBy!] = [PRIMARY_KEY_ASC]
  ): CompetitionsEdge
}

"""All input for the `updateCompetitionScoreById` mutation."""
input UpdateCompetitionScoreByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  An object where the defined keys will be set on the `CompetitionScore` being updated.
  """
  competitionScorePatch: CompetitionScorePatch!
  id: UUID!
}

"""All input for the `updateCompetitionScore` mutation."""
input UpdateCompetitionScoreInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `CompetitionScore` to be updated.
  """
  nodeId: ID!

  """
  An object where the defined keys will be set on the `CompetitionScore` being updated.
  """
  competitionScorePatch: CompetitionScorePatch!
}

"""The output of our update `CompetitionScore` mutation."""
type UpdateCompetitionScorePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `CompetitionScore` that was updated by this mutation."""
  competitionScore: CompetitionScore

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """
  Reads a single `Competition` that is related to this `CompetitionScore`.
  """
  competitionByCompetitionId: Competition

  """Reads a single `Player` that is related to this `CompetitionScore`."""
  playerByPlayerId: Player

  """An edge for our `CompetitionScore`. May be used by Relay 1."""
  competitionScoreEdge(
    """The method to use when ordering `CompetitionScore`."""
    orderBy: [CompetitionScoresOrderBy!] = [PRIMARY_KEY_ASC]
  ): CompetitionScoresEdge
}

"""All input for the `updateCourseById` mutation."""
input UpdateCourseByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  An object where the defined keys will be set on the `Course` being updated.
  """
  coursePatch: CoursePatch!
  id: UUID!
}

"""All input for the `updateCourseHandicapById` mutation."""
input UpdateCourseHandicapByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  An object where the defined keys will be set on the `CourseHandicap` being updated.
  """
  courseHandicapPatch: CourseHandicapPatch!
  id: UUID!
}

"""All input for the `updateCourseHandicap` mutation."""
input UpdateCourseHandicapInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `CourseHandicap` to be updated.
  """
  nodeId: ID!

  """
  An object where the defined keys will be set on the `CourseHandicap` being updated.
  """
  courseHandicapPatch: CourseHandicapPatch!
}

"""The output of our update `CourseHandicap` mutation."""
type UpdateCourseHandicapPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `CourseHandicap` that was updated by this mutation."""
  courseHandicap: CourseHandicap

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Player` that is related to this `CourseHandicap`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `CourseHandicap`."""
  courseByCourseId: Course

  """An edge for our `CourseHandicap`. May be used by Relay 1."""
  courseHandicapEdge(
    """The method to use when ordering `CourseHandicap`."""
    orderBy: [CourseHandicapsOrderBy!] = [PRIMARY_KEY_ASC]
  ): CourseHandicapsEdge
}

"""All input for the `updateCourse` mutation."""
input UpdateCourseInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Course` to be updated.
  """
  nodeId: ID!

  """
  An object where the defined keys will be set on the `Course` being updated.
  """
  coursePatch: CoursePatch!
}

"""The output of our update `Course` mutation."""
type UpdateCoursePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Course` that was updated by this mutation."""
  course: Course

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Course`. May be used by Relay 1."""
  courseEdge(
    """The method to use when ordering `Course`."""
    orderBy: [CoursesOrderBy!] = [PRIMARY_KEY_ASC]
  ): CoursesEdge
}

"""All input for the `updateHoleById` mutation."""
input UpdateHoleByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  An object where the defined keys will be set on the `Hole` being updated.
  """
  holePatch: HolePatch!
  id: UUID!
}

"""All input for the `updateHole` mutation."""
input UpdateHoleInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Hole` to be updated.
  """
  nodeId: ID!

  """
  An object where the defined keys will be set on the `Hole` being updated.
  """
  holePatch: HolePatch!
}

"""The output of our update `Hole` mutation."""
type UpdateHolePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Hole` that was updated by this mutation."""
  hole: Hole

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Course` that is related to this `Hole`."""
  courseByCourseId: Course

  """An edge for our `Hole`. May be used by Relay 1."""
  holeEdge(
    """The method to use when ordering `Hole`."""
    orderBy: [HolesOrderBy!] = [PRIMARY_KEY_ASC]
  ): HolesEdge
}

"""All input for the `updatePlayerById` mutation."""
input UpdatePlayerByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  An object where the defined keys will be set on the `Player` being updated.
  """
  playerPatch: PlayerPatch!
  id: UUID!
}

"""All input for the `updatePlayer` mutation."""
input UpdatePlayerInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Player` to be updated.
  """
  nodeId: ID!

  """
  An object where the defined keys will be set on the `Player` being updated.
  """
  playerPatch: PlayerPatch!
}

"""The output of our update `Player` mutation."""
type UpdatePlayerPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Player` that was updated by this mutation."""
  player: Player

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Player`. May be used by Relay 1."""
  playerEdge(
    """The method to use when ordering `Player`."""
    orderBy: [PlayersOrderBy!] = [PRIMARY_KEY_ASC]
  ): PlayersEdge
}

"""All input for the `updateScoreById` mutation."""
input UpdateScoreByIdInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  An object where the defined keys will be set on the `Score` being updated.
  """
  scorePatch: ScorePatch!
  id: UUID!
}

"""All input for the `updateScore` mutation."""
input UpdateScoreInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """
  The globally unique `ID` which will identify a single `Score` to be updated.
  """
  nodeId: ID!

  """
  An object where the defined keys will be set on the `Score` being updated.
  """
  scorePatch: ScorePatch!
}

"""The output of our update `Score` mutation."""
type UpdateScorePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Score` that was updated by this mutation."""
  score: Score

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """Reads a single `Player` that is related to this `Score`."""
  playerByPlayerId: Player

  """Reads a single `Course` that is related to this `Score`."""
  courseByCourseId: Course

  """Reads a single `Hole` that is related to this `Score`."""
  holeByHoleId: Hole

  """An edge for our `Score`. May be used by Relay 1."""
  scoreEdge(
    """The method to use when ordering `Score`."""
    orderBy: [ScoresOrderBy!] = [PRIMARY_KEY_ASC]
  ): ScoresEdge
}

"""
A universally unique identifier as defined by [RFC 4122](https://tools.ietf.org/html/rfc4122).
"""
scalar UUID

