"""The root query type which gives access points into the data universe."""
type Query implements Node {
  """
  Exposes the root query type nested one level down. This is helpful for Relay 1
  which can only query top level fields if they are in a particular form.
  """
  query: Query!

  """
  The root query type must be a `Node` to work well with Relay 1 mutations. This just resolves to `query`.
  """
  nodeId: ID!

  """Fetches an object given its globally unique `ID`."""
  node(
    """The globally unique `ID`."""
    nodeId: ID!
  ): Node

  """Reads and enables pagination through a set of `Course`."""
  allCourses(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Course`."""
    orderBy: [CoursesOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CourseCondition
  ): CoursesConnection

  """Reads and enables pagination through a set of `CourseHole`."""
  allCourseHoles(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `CourseHole`."""
    orderBy: [CourseHolesOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: CourseHoleCondition
  ): CourseHolesConnection

  """Reads and enables pagination through a set of `ExtraStrokesPerHole`."""
  allExtraStrokesPerHoles(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `ExtraStrokesPerHole`."""
    orderBy: [ExtraStrokesPerHolesOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: ExtraStrokesPerHoleCondition
  ): ExtraStrokesPerHolesConnection

  """Reads and enables pagination through a set of `HoleScore`."""
  allHoleScores(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `HoleScore`."""
    orderBy: [HoleScoresOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: HoleScoreCondition
  ): HoleScoresConnection

  """Reads and enables pagination through a set of `Player`."""
  allPlayers(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Player`."""
    orderBy: [PlayersOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: PlayerCondition
  ): PlayersConnection

  """Reads and enables pagination through a set of `Team`."""
  allTeams(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Team`."""
    orderBy: [TeamsOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: TeamCondition
  ): TeamsConnection

  """Reads and enables pagination through a set of `TeamMember`."""
  allTeamMembers(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `TeamMember`."""
    orderBy: [TeamMembersOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: TeamMemberCondition
  ): TeamMembersConnection

  """Reads and enables pagination through a set of `Tournament`."""
  allTournaments(
    """Only read the first `n` values of the set."""
    first: Int

    """Only read the last `n` values of the set."""
    last: Int

    """
    Skip the first `n` values from our `after` cursor, an alternative to cursor
    based pagination. May not be used with `last`.
    """
    offset: Int

    """Read all values in the set before (above) this cursor."""
    before: Cursor

    """Read all values in the set after (below) this cursor."""
    after: Cursor

    """The method to use when ordering `Tournament`."""
    orderBy: [TournamentsOrderBy!] = [NATURAL]

    """
    A condition to be used in determining which values should be returned by the collection.
    """
    condition: TournamentCondition
  ): TournamentsConnection
}

"""An object with a globally unique `ID`."""
interface Node {
  """
  A globally unique identifier. Can be used in various places throughout the system to identify this single value.
  """
  nodeId: ID!
}

"""A connection to a list of `Course` values."""
type CoursesConnection {
  """A list of `Course` objects."""
  nodes: [Course]!

  """
  A list of edges which contains the `Course` and cursor to aid in pagination.
  """
  edges: [CoursesEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Course` you could get from the connection."""
  totalCount: Int!
}

type Course {
  name: String
  slope: Float
  courseRating: Float
  nrHoles: BigInt
}

"""
A signed eight-byte integer. The upper big integer values are greater than the
max value for a JavaScript number. Therefore all big integers will be output as
strings and not numbers.
"""
scalar BigInt

"""A `Course` edge in the connection."""
type CoursesEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Course` at the end of the edge."""
  node: Course
}

"""A location in a connection that can be used for resuming pagination."""
scalar Cursor

"""Information about pagination in a connection."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: Cursor

  """When paginating forwards, the cursor to continue."""
  endCursor: Cursor
}

"""Methods to use when ordering `Course`."""
enum CoursesOrderBy {
  NATURAL
  NAME_ASC
  NAME_DESC
  SLOPE_ASC
  SLOPE_DESC
  COURSE_RATING_ASC
  COURSE_RATING_DESC
  NR_HOLES_ASC
  NR_HOLES_DESC
}

"""
A condition to be used against `Course` object types. All fields are tested for equality and combined with a logical ‘and.’
"""
input CourseCondition {
  """Checks for equality with the object’s `name` field."""
  name: String

  """Checks for equality with the object’s `slope` field."""
  slope: Float

  """Checks for equality with the object’s `courseRating` field."""
  courseRating: Float

  """Checks for equality with the object’s `nrHoles` field."""
  nrHoles: BigInt
}

"""A connection to a list of `CourseHole` values."""
type CourseHolesConnection {
  """A list of `CourseHole` objects."""
  nodes: [CourseHole]!

  """
  A list of edges which contains the `CourseHole` and cursor to aid in pagination.
  """
  edges: [CourseHolesEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `CourseHole` you could get from the connection."""
  totalCount: Int!
}

type CourseHole {
  holeNr: BigInt
  courseName: String
  holeIndex: BigInt
  par: BigInt
}

"""A `CourseHole` edge in the connection."""
type CourseHolesEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `CourseHole` at the end of the edge."""
  node: CourseHole
}

"""Methods to use when ordering `CourseHole`."""
enum CourseHolesOrderBy {
  NATURAL
  HOLE_NR_ASC
  HOLE_NR_DESC
  COURSE_NAME_ASC
  COURSE_NAME_DESC
  HOLE_INDEX_ASC
  HOLE_INDEX_DESC
  PAR_ASC
  PAR_DESC
}

"""
A condition to be used against `CourseHole` object types. All fields are tested
for equality and combined with a logical ‘and.’
"""
input CourseHoleCondition {
  """Checks for equality with the object’s `holeNr` field."""
  holeNr: BigInt

  """Checks for equality with the object’s `courseName` field."""
  courseName: String

  """Checks for equality with the object’s `holeIndex` field."""
  holeIndex: BigInt

  """Checks for equality with the object’s `par` field."""
  par: BigInt
}

"""A connection to a list of `ExtraStrokesPerHole` values."""
type ExtraStrokesPerHolesConnection {
  """A list of `ExtraStrokesPerHole` objects."""
  nodes: [ExtraStrokesPerHole]!

  """
  A list of edges which contains the `ExtraStrokesPerHole` and cursor to aid in pagination.
  """
  edges: [ExtraStrokesPerHolesEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """
  The count of *all* `ExtraStrokesPerHole` you could get from the connection.
  """
  totalCount: Int!
}

type ExtraStrokesPerHole {
  holeNr: BigInt
  courseName: String
  holeIndex: BigInt
  par: BigInt
  playerId: UUID
  extraStrokes: BigInt
}

"""
A universally unique identifier as defined by [RFC 4122](https://tools.ietf.org/html/rfc4122).
"""
scalar UUID

"""A `ExtraStrokesPerHole` edge in the connection."""
type ExtraStrokesPerHolesEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `ExtraStrokesPerHole` at the end of the edge."""
  node: ExtraStrokesPerHole
}

"""Methods to use when ordering `ExtraStrokesPerHole`."""
enum ExtraStrokesPerHolesOrderBy {
  NATURAL
  HOLE_NR_ASC
  HOLE_NR_DESC
  COURSE_NAME_ASC
  COURSE_NAME_DESC
  HOLE_INDEX_ASC
  HOLE_INDEX_DESC
  PAR_ASC
  PAR_DESC
  PLAYER_ID_ASC
  PLAYER_ID_DESC
  EXTRA_STROKES_ASC
  EXTRA_STROKES_DESC
}

"""
A condition to be used against `ExtraStrokesPerHole` object types. All fields
are tested for equality and combined with a logical ‘and.’
"""
input ExtraStrokesPerHoleCondition {
  """Checks for equality with the object’s `holeNr` field."""
  holeNr: BigInt

  """Checks for equality with the object’s `courseName` field."""
  courseName: String

  """Checks for equality with the object’s `holeIndex` field."""
  holeIndex: BigInt

  """Checks for equality with the object’s `par` field."""
  par: BigInt

  """Checks for equality with the object’s `playerId` field."""
  playerId: UUID

  """Checks for equality with the object’s `extraStrokes` field."""
  extraStrokes: BigInt
}

"""A connection to a list of `HoleScore` values."""
type HoleScoresConnection {
  """A list of `HoleScore` objects."""
  nodes: [HoleScore]!

  """
  A list of edges which contains the `HoleScore` and cursor to aid in pagination.
  """
  edges: [HoleScoresEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `HoleScore` you could get from the connection."""
  totalCount: Int!
}

type HoleScore {
  scorerId: UUID
  holeNr: BigInt
  courseName: String
  strokes: BigInt
  stamp: Datetime
}

"""
A point in time as described by the [ISO
8601](https://en.wikipedia.org/wiki/ISO_8601) standard. May or may not include a timezone.
"""
scalar Datetime

"""A `HoleScore` edge in the connection."""
type HoleScoresEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `HoleScore` at the end of the edge."""
  node: HoleScore
}

"""Methods to use when ordering `HoleScore`."""
enum HoleScoresOrderBy {
  NATURAL
  SCORER_ID_ASC
  SCORER_ID_DESC
  HOLE_NR_ASC
  HOLE_NR_DESC
  COURSE_NAME_ASC
  COURSE_NAME_DESC
  STROKES_ASC
  STROKES_DESC
  STAMP_ASC
  STAMP_DESC
}

"""
A condition to be used against `HoleScore` object types. All fields are tested
for equality and combined with a logical ‘and.’
"""
input HoleScoreCondition {
  """Checks for equality with the object’s `scorerId` field."""
  scorerId: UUID

  """Checks for equality with the object’s `holeNr` field."""
  holeNr: BigInt

  """Checks for equality with the object’s `courseName` field."""
  courseName: String

  """Checks for equality with the object’s `strokes` field."""
  strokes: BigInt

  """Checks for equality with the object’s `stamp` field."""
  stamp: Datetime
}

"""A connection to a list of `Player` values."""
type PlayersConnection {
  """A list of `Player` objects."""
  nodes: [Player]!

  """
  A list of edges which contains the `Player` and cursor to aid in pagination.
  """
  edges: [PlayersEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Player` you could get from the connection."""
  totalCount: Int!
}

type Player {
  id: UUID
  name: String
  sum: BigFloat
}

"""
A floating point number that requires more precision than IEEE 754 binary 64
"""
scalar BigFloat

"""A `Player` edge in the connection."""
type PlayersEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Player` at the end of the edge."""
  node: Player
}

"""Methods to use when ordering `Player`."""
enum PlayersOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  NAME_ASC
  NAME_DESC
  SUM_ASC
  SUM_DESC
}

"""
A condition to be used against `Player` object types. All fields are tested for equality and combined with a logical ‘and.’
"""
input PlayerCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `name` field."""
  name: String

  """Checks for equality with the object’s `sum` field."""
  sum: BigFloat
}

"""A connection to a list of `Team` values."""
type TeamsConnection {
  """A list of `Team` objects."""
  nodes: [Team]!

  """
  A list of edges which contains the `Team` and cursor to aid in pagination.
  """
  edges: [TeamsEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Team` you could get from the connection."""
  totalCount: Int!
}

type Team {
  teamId: UUID
  handicap: BigFloat
}

"""A `Team` edge in the connection."""
type TeamsEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Team` at the end of the edge."""
  node: Team
}

"""Methods to use when ordering `Team`."""
enum TeamsOrderBy {
  NATURAL
  TEAM_ID_ASC
  TEAM_ID_DESC
  HANDICAP_ASC
  HANDICAP_DESC
}

"""
A condition to be used against `Team` object types. All fields are tested for equality and combined with a logical ‘and.’
"""
input TeamCondition {
  """Checks for equality with the object’s `teamId` field."""
  teamId: UUID

  """Checks for equality with the object’s `handicap` field."""
  handicap: BigFloat
}

"""A connection to a list of `TeamMember` values."""
type TeamMembersConnection {
  """A list of `TeamMember` objects."""
  nodes: [TeamMember]!

  """
  A list of edges which contains the `TeamMember` and cursor to aid in pagination.
  """
  edges: [TeamMembersEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `TeamMember` you could get from the connection."""
  totalCount: Int!
}

type TeamMember {
  playerId: UUID
  teamId: UUID
}

"""A `TeamMember` edge in the connection."""
type TeamMembersEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `TeamMember` at the end of the edge."""
  node: TeamMember
}

"""Methods to use when ordering `TeamMember`."""
enum TeamMembersOrderBy {
  NATURAL
  PLAYER_ID_ASC
  PLAYER_ID_DESC
  TEAM_ID_ASC
  TEAM_ID_DESC
}

"""
A condition to be used against `TeamMember` object types. All fields are tested
for equality and combined with a logical ‘and.’
"""
input TeamMemberCondition {
  """Checks for equality with the object’s `playerId` field."""
  playerId: UUID

  """Checks for equality with the object’s `teamId` field."""
  teamId: UUID
}

"""A connection to a list of `Tournament` values."""
type TournamentsConnection {
  """A list of `Tournament` objects."""
  nodes: [Tournament]!

  """
  A list of edges which contains the `Tournament` and cursor to aid in pagination.
  """
  edges: [TournamentsEdge!]!

  """Information to aid in pagination."""
  pageInfo: PageInfo!

  """The count of *all* `Tournament` you could get from the connection."""
  totalCount: Int!
}

type Tournament {
  id: UUID
  name: String
  year: Date
}

"""The day, does not include a time."""
scalar Date

"""A `Tournament` edge in the connection."""
type TournamentsEdge {
  """A cursor for use in pagination."""
  cursor: Cursor

  """The `Tournament` at the end of the edge."""
  node: Tournament
}

"""Methods to use when ordering `Tournament`."""
enum TournamentsOrderBy {
  NATURAL
  ID_ASC
  ID_DESC
  NAME_ASC
  NAME_DESC
  YEAR_ASC
  YEAR_DESC
}

"""
A condition to be used against `Tournament` object types. All fields are tested
for equality and combined with a logical ‘and.’
"""
input TournamentCondition {
  """Checks for equality with the object’s `id` field."""
  id: UUID

  """Checks for equality with the object’s `name` field."""
  name: String

  """Checks for equality with the object’s `year` field."""
  year: Date
}

"""
The root mutation type which contains root level fields which mutate data.
"""
type Mutation {
  """Creates a single `Course`."""
  createCourse(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateCourseInput!
  ): CreateCoursePayload

  """Creates a single `CourseHole`."""
  createCourseHole(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateCourseHoleInput!
  ): CreateCourseHolePayload

  """Creates a single `HoleScore`."""
  createHoleScore(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateHoleScoreInput!
  ): CreateHoleScorePayload

  """Creates a single `TeamMember`."""
  createTeamMember(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateTeamMemberInput!
  ): CreateTeamMemberPayload

  """Creates a single `Tournament`."""
  createTournament(
    """
    The exclusive input argument for this mutation. An object type, make sure to see documentation for this object’s fields.
    """
    input: CreateTournamentInput!
  ): CreateTournamentPayload
}

"""The output of our create `Course` mutation."""
type CreateCoursePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Course` that was created by this mutation."""
  course: Course

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Course`. May be used by Relay 1."""
  courseEdge(
    """The method to use when ordering `Course`."""
    orderBy: [CoursesOrderBy!] = [NATURAL]
  ): CoursesEdge
}

"""All input for the create `Course` mutation."""
input CreateCourseInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `Course` to be created by this mutation."""
  course: CourseInput!
}

"""An input for mutations affecting `Course`"""
input CourseInput {
  name: String
  slope: Float
  courseRating: Float
  nrHoles: BigInt
}

"""The output of our create `CourseHole` mutation."""
type CreateCourseHolePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `CourseHole` that was created by this mutation."""
  courseHole: CourseHole

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `CourseHole`. May be used by Relay 1."""
  courseHoleEdge(
    """The method to use when ordering `CourseHole`."""
    orderBy: [CourseHolesOrderBy!] = [NATURAL]
  ): CourseHolesEdge
}

"""All input for the create `CourseHole` mutation."""
input CreateCourseHoleInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `CourseHole` to be created by this mutation."""
  courseHole: CourseHoleInput!
}

"""An input for mutations affecting `CourseHole`"""
input CourseHoleInput {
  holeNr: BigInt
  courseName: String
  holeIndex: BigInt
  par: BigInt
}

"""The output of our create `HoleScore` mutation."""
type CreateHoleScorePayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `HoleScore` that was created by this mutation."""
  holeScore: HoleScore

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `HoleScore`. May be used by Relay 1."""
  holeScoreEdge(
    """The method to use when ordering `HoleScore`."""
    orderBy: [HoleScoresOrderBy!] = [NATURAL]
  ): HoleScoresEdge
}

"""All input for the create `HoleScore` mutation."""
input CreateHoleScoreInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `HoleScore` to be created by this mutation."""
  holeScore: HoleScoreInput!
}

"""An input for mutations affecting `HoleScore`"""
input HoleScoreInput {
  scorerId: UUID
  holeNr: BigInt
  courseName: String
  strokes: BigInt
  stamp: Datetime
}

"""The output of our create `TeamMember` mutation."""
type CreateTeamMemberPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `TeamMember` that was created by this mutation."""
  teamMember: TeamMember

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `TeamMember`. May be used by Relay 1."""
  teamMemberEdge(
    """The method to use when ordering `TeamMember`."""
    orderBy: [TeamMembersOrderBy!] = [NATURAL]
  ): TeamMembersEdge
}

"""All input for the create `TeamMember` mutation."""
input CreateTeamMemberInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `TeamMember` to be created by this mutation."""
  teamMember: TeamMemberInput!
}

"""An input for mutations affecting `TeamMember`"""
input TeamMemberInput {
  playerId: UUID
  teamId: UUID
}

"""The output of our create `Tournament` mutation."""
type CreateTournamentPayload {
  """
  The exact same `clientMutationId` that was provided in the mutation input,
  unchanged and unused. May be used by a client to track mutations.
  """
  clientMutationId: String

  """The `Tournament` that was created by this mutation."""
  tournament: Tournament

  """
  Our root query field type. Allows us to run any query from our mutation payload.
  """
  query: Query

  """An edge for our `Tournament`. May be used by Relay 1."""
  tournamentEdge(
    """The method to use when ordering `Tournament`."""
    orderBy: [TournamentsOrderBy!] = [NATURAL]
  ): TournamentsEdge
}

"""All input for the create `Tournament` mutation."""
input CreateTournamentInput {
  """
  An arbitrary string value with no semantic meaning. Will be included in the
  payload verbatim. May be used to track mutations by the client.
  """
  clientMutationId: String

  """The `Tournament` to be created by this mutation."""
  tournament: TournamentInput!
}

"""An input for mutations affecting `Tournament`"""
input TournamentInput {
  id: UUID
  name: String
  year: Date
}
