# .github/workflows/pgtest.yml
#
## A simple GH action for running the DB unit tests
#
name: Postgres tests

on: push

jobs:
  pgtap:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg-version: [ '17' ]

    services:
      postgres:
        image: oleorhagen89/postgresql-pgtap:latest
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: golf_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - name: install pg_prove
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash

      - name: load sql
        run: >-
          for f in backend/sql/*.sql; do
            psql --host localhost --username postgres --dbname golf_db \
                --file $f
          done
        env:
          PGPASSWORD: password

      - name: run tests
        run: >-
          pg_prove                  \
                --host localhost    \
                --dbname golf_db    \
                --username postgres \
                  backend/sql-tests/*
        env:
          PGPASSWORD: password
